/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package1;
// Generated 24 Mar, 2020 7:43:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class CustMaster  implements java.io.Serializable {

    private Integer CID;
    private String CustName;
    private String PANNo;
    private String Gender;
    private String City;
    private String Address;
    private Integer MobileNo;
    private Integer AlternateNo;
    private String Dob;
    private String Status;
     //private Set emis = new HashSet(0);
   // private Set emi2s = new HashSet(0);
    public CustMaster(){
        
    }
    public CustMaster(Integer CID, String CustName, String PANNo, String Gender, String city, String Address, Integer MobileNo, Integer AlternateNo, String Dob, String status)
    {
        this.CID=CID;
        this.CustName=CustName;
        this.PANNo=PANNo;
        this.Gender=Gender;
        this.City=city;
        this.Address=Address;
        this.MobileNo=MobileNo;
        this.AlternateNo=AlternateNo;
        this.Dob=Dob;
        this.Status=status;
               
    }
    /*public CustMaster(Integer CID, String CustName, String PANNo, String Gender, String city, String Address, Integer MobileNo, Integer AlternateNo, String Dob, String status, Set emi2s)
    {
        this.CID=CID;
        this.CustName=CustName;
        this.PANNo=PANNo;
        this.Gender=Gender;
        this.City=city;
        this.Address=Address;
        this.MobileNo=MobileNo;
        this.AlternateNo=AlternateNo;
        this.Dob=Dob;
        this.Status=status;
        this.emi2s=emi2s;       
    }*/
    /*public CustMaster(Integer CID, String CustName, String PANNo, String Gender, String city, String Address, Integer MobileNo, Integer AlternateNo, String Dob, String status, Set emis)
    {
        this.CID=CID;
        this.CustName=CustName;
        this.PANNo=PANNo;
        this.Gender=Gender;
        this.City=city;
        this.Address=Address;
        this.MobileNo=MobileNo;
        this.AlternateNo=AlternateNo;
        this.Dob=Dob;
        this.Status=status;
        this.emis=emis;     
    }*/
   public Integer getCID(){
       return this.CID;
   }
   public void setCID(Integer CID){
       this.CID=CID;
   }
   public String getCustName(){
       return this.CustName;
   }
   public void setCustName(String CustName){
       this.CustName=CustName;
   }
   public String getPANNo(){
       return this.PANNo;
   }
   public void setPANNo(String PANNo){
       this.PANNo=PANNo;
   }
   public String getGender(){
       return this.Gender;
   }
   public void setGender(String Gender){
       this.Gender=Gender;
   }
   public String getCity(){
       return this.City;
   }
   public void setCity(String City){
       this.City=City;
   }
   public String getAddress(){
       return this.Address;
   }
   public void setAddress(String Address){
       this.Address=Address;
   }
   public Integer getMobileNo(){
       return this.MobileNo;
   }
   public void setMobileNo(Integer MobileNo){
       this.MobileNo=MobileNo;
   }
 
    public Integer getAlternateNo(){
       return this.AlternateNo;
   }
   public void setAlternateNo(Integer AlternateNo){
       this.AlternateNo=AlternateNo;
   }
     public String getDob(){
       return this.Dob;
   }
   public void setDob(String Dob){
       this.Dob=Dob;
   }
    public String getStatus(){
       return this.Status;
   }
   public void setStatus(String Status){
       this.Status=Status;
   }

    /*public Set getEmis() {
        return this.emis;
    }
    
    public void setEmis(Set emis) {
        this.emis= emis;
    }*/

  /*public Set getEmi2s() {
        return this.emi2s;
    }
    
    public void setEmi2s(Set emi2s) {
        this.emi2s = emi2s;
    }*/


}



