package package1;
// Generated 24 Mar, 2020 7:43:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer custId;
     private String firstName;
     private String lastName;
     private String accountType;
     private float balance;
     private Set studentLoanses = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String firstName, String lastName, String accountType, float balance) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.accountType = accountType;
        this.balance = balance;
    }
    public Customer(String firstName, String lastName, String accountType, float balance, Set studentLoanses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.accountType = accountType;
       this.balance = balance;
       this.studentLoanses = studentLoanses;
    }
   
    public Integer getCustId() {
        return this.custId;
    }
    
    public void setCustId(Integer custId) {
        this.custId = custId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
    public float getBalance() {
        return this.balance;
    }
    
    public void setBalance(float balance) {
        this.balance = balance;
    }
    public Set getStudentLoanses() {
        return this.studentLoanses;
    }
    
    public void setStudentLoanses(Set studentLoanses) {
        this.studentLoanses = studentLoanses;
    }




}


