package package1;
// Generated 24 Mar, 2020 7:43:04 PM by Hibernate Tools 4.3.1



/**
 * LoanInfo generated by hbm2java
 */
public class LoanInfo  implements java.io.Serializable {


     private Integer requestId;
     private String requestType;
     private int approvedRejected;

    public LoanInfo() {
    }

    public LoanInfo(String requestType, int approvedRejected) {
       this.requestType = requestType;
       this.approvedRejected = approvedRejected;
    }
   
    public Integer getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }
    public String getRequestType() {
        return this.requestType;
    }
    
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }
    public int getApprovedRejected() {
        return this.approvedRejected;
    }
    
    public void setApprovedRejected(int approvedRejected) {
        this.approvedRejected = approvedRejected;
    }




}


