package package1;
// Generated 24 Mar, 2020 7:43:04 PM by Hibernate Tools 4.3.1



/**
 * ManagerDetails generated by hbm2java
 */
public class ManagerDetails  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String branchName;

    public ManagerDetails() {
    }

    public ManagerDetails(String username, String password, String firstName, String lastName, String branchName) {
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.branchName = branchName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }




}


