package package1;
// Generated 24 Mar, 2020 7:43:04 PM by Hibernate Tools 4.3.1



/**
 * StudentLoans generated by hbm2java
 */
public class StudentLoans  implements java.io.Serializable {


     private Integer requestId;
     private Customer customer;
     private int Amount;
     private int age;
     private String instituteName;
     private String course;
     private byte[] proofOfIdentity;
     private byte[] incomeProof;
     private byte[] educationProof;
     private int status;
    public StudentLoans() {
    }

    public StudentLoans(Customer customer, int Amount, int age, String instituteName, String course, byte[] proofOfIdentity, byte[] incomeProof, byte[] educationProof, int status) {
       this.customer = customer;
       this.age = age;
       this.instituteName = instituteName;
       this.course = course;
       this.proofOfIdentity = proofOfIdentity;
       this.incomeProof = incomeProof;
       this.educationProof = educationProof;
       this.Amount=Amount;
       this.status=status;
    }
   
    public Integer getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public int getAmount(){
        return this.Amount;
    }
    public void setAmount(int Amount){
        this.Amount=Amount;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getInstituteName() {
        return this.instituteName;
    }
    
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName;
    }
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }
    public byte[] getProofOfIdentity() {
        return this.proofOfIdentity;
    }
    
    public void setProofOfIdentity(byte[] proofOfIdentity) {
        this.proofOfIdentity = proofOfIdentity;
    }
    public byte[] getIncomeProof() {
        return this.incomeProof;
    }
    
    public void setIncomeProof(byte[] incomeProof) {
        this.incomeProof = incomeProof;
    }
    public byte[] getEducationProof() {
        return this.educationProof;
    }
    
    public void setEducationProof(byte[] educationProof) {
        this.educationProof = educationProof;
    }
     public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }



}


